name: main

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup nodev14.17.6
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.6'

      - name: Install packages
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Install Yarn Globally # used for the testing step below
        run: npm install yarn --global

      - name: Test
        run: npm run test
        env:
          CI: true
