name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v2

      - name: Setup nodev14.17.6
      - uses: actions/setup-node@v1
        with:
          node-version: '14.17.6'

      - name: Install packages
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: gitTagger
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: 'none'
          WITH_V: false

      - name: Publish to npm
        if: ${{ contains(join(github.event.commits.*.message, ' '), '#publish') }}
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{steps.gitTagger.outputs.tag}}
